version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" # "daily", "weekly", "monthly"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-*"
        versions: ["2.3.x", "2.5.x"]
    commit-message:
      prefix: "chore" # Prefix title and commit message with a string
      include: "scope" #  Include the package scope in the commit message
