extends: default

rules:
  line-length: disable
  empty-lines: disable
  comments: disable
  comments-indentation: disable
  document-start: disable
  truthy: disable
  trailing-spaces: disable
  new-line-at-end-of-file: disable
  indentation: disable
  quoted-strings:
    required: false
    extra-required:
      - "^\\d{15,}$"  # Enforce quotes for numbers with 15+ digits
    extra-allowed: []
    allow-quoted-quotes: false
    check-keys: false