extends: default
ignore:
  - "ub/workflows/blank.yml"  # Ignore this specific file
  - "ub/workflows/*.yml"       # Ignore all YAML files in the 'ub/workflows' directory
  - "**/workflows/**"           # Ignore any 'workflows' directory at any level

rules:
  line-length: disable
  empty-lines: disable
  comments: disable
  comments-indentation: disable
  document-start: disable
  truthy: disable
