extends: default

rules:
  line-length: disable
  empty-lines: disable
  comments: disable
  comments-indentation: disable
  document-start: disable
  truthy: disable
  quoted-strings:
    level: error
    required: false
    extra-required:
      - "^\\d{15,}$"  # Enforce quotes for numbers with 15+ digits
    quote-type: any