name: YAML Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: yamllint
        uses: nosborn/github-action-yamllint@v1

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Run yamllint on YAML files for syntax errors only
        run: |
          yamllint -s . -f parsable  # Only check for syntax errors using the custom config
