name: Check YAML Files

on:
  pull_request:
    branches:
      - main

jobs:
  check-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: |
          yamllint ./**/*.yaml --strict --format=standard > yaml_lint_report.json
      - name: Check for lint errors
        run: |
          if [ $(jq '.[].level' yaml_lint_report.json | wc -l) -gt 0 ]; then
            echo "YAML linting found errors. Check yaml_lint_report.json for details."
            exit 1
          fi
