name: YAML Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Run yamllint on YAML files for syntax errors only
        run: |
          yamllint -s . -f parsable # Only check for syntax errors

      - name: Check for any YAML files with syntax errors
        run: |
          yamllint . -f parsable # Check all YAML files, including syntax errors
