name: Check PR Syntax

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check YAML syntax
        uses: mpalmer/action-validator@v0.5.1
        with:
          paths: |
            .github/workflows/*.yml
            .github/actions/*.yml
