name: YAML Parsing Check

on:
  pull_request:
    branches:
      - main

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install yamllint
      run: |
        sudo apt-get update
        sudo apt-get install -y yamllint

    - name: Run yamllint on YAML files with detailed output
      run: |
        yamllint . -f parsable

    - name: Check for format issues (strict mode)
      run: |
        yamllint --strict . -f parsable
