name: 'Yamllint GitHub Actions'

on:
  pull_request

jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.' # Lint all YAML files in the repository
          yamllint_strict: false # Set to true if you want stricter linting
          yamllint_comment: true # Adds a comment on PR if linting fails
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
